import express from 'express';
import cors from 'cors';
import aiRouter from './routes/ai.js';
import tasksRouter from './routes/tasks.js';
import historyRouter from './routes/history.js';
import notifRouter from './routes/notifications.js';
const app = express();
app.use(cors());
app.use(express.json({ limit: '64kb' }));
app.get('/api/health', (req, res) => res.json({ ok: true }));
app.use('/api/ai', aiRouter);
app.use('/api/tasks', tasksRouter);
app.use('/api/history', historyRouter);
app.use('/api/notifications', notifRouter);
export default app;
